### PR TITLE
[Bitbucket] Adding ability to fork a repo to a different project

### PR DESCRIPTION
**Pull request by zacaryc**
Adding ability to fork a repo to a different project that differs from the original source project, which is what the existing
functionality is limited to.

Within a fair few of my workflows and projects I work with, we need to fork the original project to a personal user repo make changes and create pull requests back. Unfortunately in trying to automate these I'm limited in the ability of using this library to be able to bootstrap the workflow.

This is doing the bare minimum fork without adding in any extra properties like fork syncing etc to add the smallest change first that matches the existing mono-project fork.

### CODE REVIEW

**Comment by zacaryc** [comment]
Noticing that every PR that's raised recently seems to be failing the Test run on the same step.
Is it stable/failing on master already and these are false negatives? Or is there something missing here to be added to test code, for my PR?

**Comment by gonchik** [comment]
Thanks! :) 
Please, provide for the next time a docs.

**Comment by zacaryc** [comment]
@gonchik thank you. 
No worries I'll write up some docs now actually, I noticed the regular fork was missing them as well.

**Comment by zacaryc** [comment]
https://github.com/atlassian-api/atlassian-python-api/pull/852 created for docs

**Pull request merged**
