### PR TITLE
Kerberos follow-up

### PR DESCRIPTION
**Pull request by offa**
Some open issues mentioned in #353 fixed:

1. Exception if kerberos is used but not installed
1. Tox config updated to include the extra dependency
1. Note added to the documentation. Is this enough or is a full pip call more suitable?

### CODE REVIEW

**Comment by offa** [comment]
The installation of optional dependencies through the pypi package doesn't work.

```sh
> pip install atlassian-python-api[kerberos]
```
Results in _No matches found_.

It works from source and the installed package contains some sort of dependency information (`requires.txt`) :thinking: :

```ini
requests
six
oauthlib
requests_oauthlib

[kerberos]

[kerberos:platform_system != "Windows"]
kerberos

[kerberos:platform_system == "Windows"]
kerberos-sspi
```

**Comment by offa** [comment]
Well … quotes to the trick:

```sh
pip install "atlassian-python-api[kerberos]"
```

And it works! :+1:

**Comment by offa** [comment]
There's just on issue left: How to handle the `requirements.txt`?

1. Move kerberos to a seperate one which sources the common file
1. Keep all dependencies in one file as it's at the moment

Are there any preferences?

**Comment by gonchik** [comment]
I think the better way is keep in one file, as we can number of dependency.

**Comment by offa** [comment]
So, then the PR is ready from my side.

**Comment by gonchik** [comment]
Thank you :)

**Pull request merged**
