### PR TITLE
[BITBUCKET] Allow users to use filter on pipeline

### PR DESCRIPTION
**Pull request by Amnesycks**
Adding filter "page" & "pagelen" on pipeline.each()
This can allow to use workaround on #740 as mention in https://jira.atlassian.com/browse/BCLOUD-13806

### CODE REVIEW

**Comment by Spacetown** [comment]
@gonchik I think it is better to do the pagination workaround inernal and not add parameters for this. Also the documentation for the parameters is missing.

**Comment by Amnesycks** [comment]
The pagination on API, work with GET parameters like "sorting", it's why I added this with parameters. About documenting I don't see where the parameters are, only methods. Tell me where and I will update this soon when I got a bit of time to work on it.

**Comment by Spacetown** [comment]
@Amnesycks The arguments are described inside the function:
https://github.com/atlassian-api/atlassian-python-api/blob/a863ad779fb7c8199d6ba037fd8189e9710ca7e7/atlassian/bitbucket/cloud/repositories/pipelines.py#L66-L69

The paging is done internal and hidden from the user:
https://github.com/atlassian-api/atlassian-python-api/blob/a863ad779fb7c8199d6ba037fd8189e9710ca7e7/atlassian/bitbucket/cloud/repositories/pipelines.py#L84-L85

I can make a suggestion for doing the workaround inside the function without user interaction.

**Comment by Spacetown** [comment]
What do you think about the suggestion? Maybe the arguments `page` and `pagelen` can be removed again.

**Comment by Amnesycks** [comment]
Hello @Spacetown, My bad i absolutely not think to docstrings :disappointed:. Your suggestion seems good, I don't tested it, but the logic seems better, so in my opinion we should keep yours.

**Comment by Spacetown** [comment]
@Amnesycks No problem. Can you check this on your site because you had the problem?

**Pull request merged**
