### PR TITLE
[Bitbucket Cloud] Pull Request Builds

### PR DESCRIPTION
**Pull request by sti0**
As mentioned in #662. This adds the relation betwenn pull request and pipelines.

To discuss:

- To prevent circular dependencies: Whats in lead? PR or pipeline.
- Pipeline returns full PR object
- By hijhacking the pull request statuses we can get the build number of the most recent pipelines (via regex @ `url` or `name`)
- Are the pr statuses useful? Example, two pipelines (one triggered by PR, one by branch/push)
```
{
    "pagelen": 30,
    "values": [
        {
            "key": "-432121212",
            "description": "",
            "repository": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/workspace_slag/repo_slag"
                    },
                    "html": {
                        "href": "https://bitbucket.org/workspace_slag/repo_slag"
                    },
                    "avatar": {
                        "href": "https://bytebucket.org/ravatar/%7Brepo_uuid%7D?ts=default"
                    }
                },
                "type": "repository",
                "name": "repo_slag",
                "full_name": "workspace_slag/repo_slag",
                "uuid": "{repo_uuid}"
            },
            "url": "https://bitbucket.org/workspace_slag/repo_slag/addon/pipelines/home#!/results/122",
            "links": {
                "commit": {
                    "href": "https://api.bitbucket.org/2.0/repositories/workspace_slag/repo_slag/commit/9827b6e74d796e0732ad5d1b3e0b30192342e8c7"
                },
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/workspace_slag/repo_slag/commit/9827b6e74d796e0732ad5d1b3e0b30192342e8c7/statuses/build/-432121212"
                }
            },
            "refname": "feature/mybranch",
            "state": "SUCCESSFUL",
            "created_on": "2020-12-28T10:23:11.271567+00:00",
            "commit": {
                "hash": "9827b6e74d796e0732ad5d1b3e0b30192342e8c7",
                "type": "commit",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/workspace_slag/repo_slag/commit/9827b6e74d796e0732ad5d1b3e0b30192342e8c7"
                    },
                    "html": {
                        "href": "https://bitbucket.org/workspace_slag/repo_slag/commits/9827b6e74d796e0732ad5d1b3e0b30192342e8c7"
                    }
                }
            },
            "updated_on": "2020-12-28T10:24:20.786070+00:00",
            "type": "build",
            "name": "Pipeline #122 for feature/mybranch"
        },
        {
            "key": "220449332",
            "description": "",
            "repository": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/workspace_slag/repo_slag"
                    },
                    "html": {
                        "href": "https://bitbucket.org/workspace_slag/repo_slag"
                    },
                    "avatar": {
                        "href": "https://bytebucket.org/ravatar/%7Brepo_uuid%7D?ts=default"
                    }
                },
                "type": "repository",
                "name": "repo_slag",
                "full_name": "workspace_slag/repo_slag",
                "uuid": "{repo_uuid}"
            },
            "url": "https://bitbucket.org/workspace_slag/repo_slag/addon/pipelines/home#!/results/123",
            "links": {
                "commit": {
                    "href": "https://api.bitbucket.org/2.0/repositories/workspace_slag/repo_slag/commit/9827b6e74d796e0732ad5d1b3e0b30192342e8c7"
                },
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/workspace_slag/repo_slag/commit/9827b6e74d796e0732ad5d1b3e0b30192342e8c7/statuses/build/220449332"
                }
            },
            "refname": "feature/SA-5-erzielte-spanne",
            "state": "SUCCESSFUL",
            "created_on": "2020-12-28T10:23:11.317962+00:00",
            "commit": {
                "hash": "9827b6e74d796e0732ad5d1b3e0b30192342e8c7",
                "type": "commit",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/workspace_slag/repo_slag/commit/9827b6e74d796e0732ad5d1b3e0b30192342e8c7"
                    },
                    "html": {
                        "href": "https://bitbucket.org/workspace_slag/repo_slag/commits/9827b6e74d796e0732ad5d1b3e0b30192342e8c7"
                    }
                }
            },
            "updated_on": "2020-12-28T10:25:04.865975+00:00",
            "type": "build",
            "name": "Pipeline #123 for Pull Request #1"
        }
    ],
    "page": 1,
    "size": 2
}
```

### CODE REVIEW

**Comment by Spacetown** [comment]
> * To prevent circular dependencies: Whats in lead? PR or pipeline.
> * Pipeline returns full PR object

I think PR is lead. From pipeline side you can use lazy loading to get the PR.
 
> * By hijhacking the pull request statuses we can get the build number of the most recent pipelines (via regex @ `url` or `name`)

Sorry, I don't understand the point.

> * Are the pr statuses useful? Example, two pipelines (one triggered by PR, one by branch/push)

Of course, they are needed for merge checks.

**Comment by sti0** [comment]
> > * By hijhacking the pull request statuses we can get the build number of the most recent pipelines (via regex @ `url` or `name`)
> 
> Sorry, I don't understand the point.

As you can see in the example there is no direct url for the pipeline endpoint. In that case we could only extract the unique build_number out of the URL (``https://bitbucket.org/workspace_slag/repo_slag/addon/pipelines/home#!/results/**123**``) or out of the name (``Pipeline #123 for Pull Request #1``). Maybe you've got an other solution.

**Comment by Spacetown** [comment]
But the example is from a pipeline and not from a PR. Do you want to get the most recent pipeline of a PR?

**Comment by sti0** [comment]
> But the example is from a pipeline and not from a PR. Do you want to get the most recent pipeline of a PR?

Its the response of the PR statuses endpoint. I didn't find any other point to reference to the pipeline.
The pipeline endpoint returns the full PR object.

**Comment by Spacetown** [comment]
Now I got it. To get the ID the url should be used because I don't know if the description is fixed. But to get the pipeline you need the uuid and not the build number. Here you will need https://developer.atlassian.com/bitbucket/api/2/reference/meta/filtering.

**Comment by sti0** [comment]
You could even use the `build_number` instead of `uuid`. This works, too.

**Comment by Spacetown** [comment]
I like undocumented features...

**Comment by gonchik** [comment]
@sti0 
Once you're ready, please, ping me :)

**Comment by sti0** [comment]
@gonchik @Spacetown 
Sorry I've been busy for a while. Now I finished the work on this.

My last change introduces a new class called `Build`, instead of doing some workarounds to try to get the pipelines from the pull request. We get now the builds for the pull request. In this case someone who use other CI tools like Jenkins, Circle CI etc. can also use this endpoint. If the user like to refer to pipelines this must be done by extra work (regex etc.). This is because there is no garantuee that the logic (cut out the build number and use it as key for pipeline) will work in the future.

At pipeline level we still reference to the associated pull request.

**Pull request merged**
