### PR TITLE
Commit Object addition to Pull Requests - #1251

### PR DESCRIPTION
**Pull request by isaac-philip**
- PullRequest object to contain the Commits 
- Example added 
- Test-case added

Closes Issue #1251

### CODE REVIEW

**Comment by gonchik** [comment]
@isaac-philip  could you finalize the PR  please?

**Comment by isaac-philip** [comment]
yes will have a look, thanks!

**Comment by gonchik** [comment]
@isaac-philip  Thanks!

**Comment by isaac-philip** [comment]
Thanks @gonchik for taking it ahead, was out due to a health emergency, just checked.

**Pull request merged**
