### PR TITLE
Support OAuth authentication

### PR DESCRIPTION
**Pull request by joshwarren**
Add Oauth capabilities as well as the basic username and password. Username and password should become optional

### CODE REVIEW

**Comment by gonchik** [comment]
Hi @joshwarren , 

Thanks for that PR. :) 
I would like to test that change on my test env?  
I would add into requirements additional dependency.
 
Cheers,
Gonchik Tsymzhitov

**Comment by joshwarren** [comment]
Ah yes I've updated both setup.py and requirements.txt. Apologies this is my first pull request!

**Comment by gonchik** [comment]
Thanks for that input :)

**Comment by gonchik** [comment]
I hope someone from that request #144 will be interested as well :)

**Comment by gonchik** [comment]
Thank you again! :)

**Pull request merged**
