### PR TITLE
All: Fixes typos

### PR DESCRIPTION
**Pull request by jensvog**
Scanned over whole repository and fixes some typos.

### CODE REVIEW

**Comment by Spacetown** [comment]
Fixes in comments are welcome but fixes in function names are incompatible changes.

**Comment by gonchik** [comment]
@Spacetown  as I see only 2 method were renamed. 

I think better to merge with small wrapper rule. 

 ``` 
@deprecated 
def delete_pull_reques_comment(self,repository_slug,
        pull_request_id,
        comment_id,	
        comment_version,	        
    ):
"""
Typo will be removed
"""
 return self.delete_pull_request_comment(repository_slug,
        pull_request_id,
        comment_id,	
        comment_version)
```

**Comment by Spacetown** [comment]
The second one already had a wrapper rule but with a log entry instead of `@deprecated` decorator.

**Comment by jensvog** [comment]
Thanks for your feedback. I created an update.

* The confluence method already had a hint and a corrected method. Thanks for the hint @Spacetown. I reverted the typo change there.
* I updated the bitbucket function so that the typo method is marked as deprecated and added a method with correct function name, like you supposed @gonchik.

How does it look now to you?

**Pull request merged**
