### PR TITLE
feat(insight): implement get objectschema objecttypes flat

### PR DESCRIPTION
**Pull request by gardar**

### CODE REVIEW

**Comment by gonchik** [comment]
@gardar thank you! :) 
also, I will be happy if you add some word into insight.rst file ;)

**Comment by gardar** [comment]
> also, I will be happy if you add some word into insight.rst file ;) 

Sure, but where is it located?

**Comment by gonchik** [comment]
@gardar it's not generating automatically :(

**Comment by gardar** [comment]
> @gardar it's not generating automatically :( 
> 

I would think that would be trivial to add, since you are already using sphinx and have docstrings for most functions, you even have the autodoc extension loaded 🙂

https://www.sphinx-doc.org/en/master/tutorial/automatic-doc-generation.html

**Comment by gonchik** [comment]
@gardar  will be happy if you fix that :)

**Pull request merged**
