### PR TITLE
[Tests] Add pyproject.toml for pylint, black and flake

### PR DESCRIPTION
**Pull request by Spacetown**
- Move content of pylintrc to pyproject.toml.
- Configure the line length to 120 also for black

### CODE REVIEW

**Comment by Spacetown** [comment]
@gonchik Please configure the github actions to be required for merging. Shall I also deactivate the travis builds?

**Comment by gonchik** [comment]
deleted the webhook to Travis

**Comment by gonchik** [comment]
@Spacetown Yes, please. Feel free to deactivate the travis ci.

**Comment by gonchik** [comment]
@Spacetown  Let's full deactivate on next release. 
I got a few emails related to the compatibility with 2.7. 
Still many servers are using 2.7.

**Comment by Spacetown** [comment]
In GitHub actions the PIP output was:
```DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.```
I can add the test for 2.7 in January it will fail.

**Comment by gonchik** [comment]
No need :) 
Just keep the "".format string formatting instead of awesome f"" for now.
I think in 6 months, we can drop off the 2.7 support fully

**Pull request merged**
