### PR TITLE
[Bitbucket] Unification and url generate cleanup [outdated]

### PR DESCRIPTION
**Pull request by fedordikarev**
I think it could be good idea to remove `if not self.cloud` statements and use property for that and special methods like `self._get_api()` and `self._put_api()` to make api calls.
Here I replace almost all `self.put` for example. What do you think?
Should I continue with that changes?

### CODE REVIEW

**Comment by pylipp** [comment]
I think the URL generation could take some refactoring, so this PR is a good start.
However I'd make use of the `api_root` and `api_version` attributes and the `resource_url()` method of `AtlassianRestAPI` instead of introducing new methods. I used this method in #477.

**Comment by gonchik** [comment]
I just thinking about that parameters as well.
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/rest_client.py#L24

**Comment by Spacetown** [comment]
Oops, I did also a refactoring with #609 which was merged today.
Currently I'm working on a object oriented implementation of the API.

**Comment by gonchik** [comment]
Closing as it's confusing

**Pull request closed without merging**
