### PR TITLE
[JIRA] Issues export to CSV +current fields option

### LINKED ISSUE #602: [JIRA] Issues export to CSV - CURRENT FIELDS option
### :chart_with_upwards_trend: Improvement
- Presently we have ability to export `ALL fields` 
- but there is an api endpoint which can provide ability to take a smaller set such as of `current fields`

### :heavy_plus_sign: Provision
- option provided and based on that the csv data of ALL fields or current fields will be returned
- defaulting to ALL FIELDS to not break existing code/usage

### :warning: Checklist during Peer Review 
- non breaking existing functionality

### PR DESCRIPTION
**Pull request by isaac-philip**
To provide option to export CURRENT fields also in addition to existing ALL fields

Default : ALL fields (existing and non-breaking change)

- Functionality addition in `atlassian/jira`
- Example added
- Constants file added to have project related constants
- Docs example added

Closes #602

### CODE REVIEW

**Comment by gonchik** [comment]
Hi! 
First of all, thank you for your pull request. 
One thing, what is the purpose to make contans.py file ?
Is it possible wrap into more generic way?

**Comment by isaac-philip** [comment]
Hello @gonchik 
so let me explain purpose of constants.py

aiming to have DRY with the urls and so on.
any constants can go here to be referenced in other files.
good practice to refer URI/URL(s) as constant rather than declaring at usage.

if i have same URI duplicated in the jira.py then thats against DRY.
this will help to reduce redundancy right.

_just beginning to go towards linting and other checks of quality on code.
beginning to prepare towards it_

let me know your views. 😊

**Comment by isaac-philip** [comment]
Hello @gonchik ,

any changes required to close this?

**Comment by gonchik** [comment]
Hi @isaac-philip , 
can we postpone for now the constants.py ? 
Because it's unclear in the future how to manage it for all others rest end point, I mean for confluence, bamboo etc,

**Pull request merged**
