### PR TITLE
Add more Crowd functions

### PR DESCRIPTION
**Pull request by ChowRex**
- Add a new function `user_groups` used to get specify user's all group info
- Introduce new dependencies `jmespath` which is used for search string in json, for more info, read: [JMESPath Tutorial — JMESPath](https://jmespath.org/tutorial.html)
- Using universal request to get user's group, controled by `kind` param
- Using universal request to get group's member, controled by `kind` param
- Add a new function to determine whether the user is a member of a group
- Add a parameter `max_results` has prevented insufficient results from being returned, the server default is `1000`

### CODE REVIEW

**Comment by ChowRex** [comment]
Add 2 more commits to fix RTD doc build error.

**Comment by ChowRex** [comment]
After dig into the `Dockerfile.qa`, I found your are using the `requirement-dev.txt` not the `requirements.txt` to install the required packages then check QA result, so I have added it into it now.

**Comment by ChowRex** [comment]
Add doc

**Comment by gonchik** [comment]
@ChowRex thank you for your PR and fix docs 
As I see jmasepath is quite sweet syntax for json :)

Let's start from that usage. 
It will be nice if you made more PRs :)

**Comment by ChowRex** [comment]
@gonchik Thanks for reply, I'm trying to fix the QA testing errors. If time permits, I'd be happy to submit more PRs.

**Comment by ChowRex** [comment]
Close the PR for the time being, and I will resubmit it after repair.

**Comment by ChowRex** [comment]
Reopen this PR.

**Pull request merged**
