### PR TITLE
[BitBucket] Add exists function to clound and server OO interface.

### LINKED ISSUE #757: Bitbucket Cloud lacks the "project_exists" and "repo_exists" methods available for Server
So I'm running into this issue whereby attempting to create a project that already exists returns a 400 from Bitbucket Cloud. This seems makes sense and seems expected because looking at the [Projects class](https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket/cloud/workspaces/projects.py), it's using a POST operation for the "create" method.

Here's my code:

```
bitbucket_cloud = Cloud(
    url = 'https://api.bitbucket.org/',
    username=args.cloud_user,
    password=args.cloud_pass,
    cloud=True
)

args.workspace = "a-workspace-name"

bitbucket_cloud.workspaces.get(args.workspace)projects.create(
    key="ABC",
    name="ABC Project",
    description="A useful description",
    is_private=True
)
```

This returns:

```
Traceback (most recent call last):
  File "src/bbmigrate/cli2.py", line 80, in <module>
    bitbucket_cloud.workspaces.get(args.cloud_workspace).projects.create(
  File "/home/mdavis/.local/share/virtualenvs/bb-server-cloud-migrate-h2IgRdlA/lib/python3.8/site-packages/atlassian/bitbucket/cloud/workspaces/projects.py", line 48, in create
    return self.__get_object(self.post(None, data=data))
  File "/home/mdavis/.local/share/virtualenvs/bb-server-cloud-migrate-h2IgRdlA/lib/python3.8/site-packages/atlassian/rest_client.py", line 303, in post
    response = self.request(
  File "/home/mdavis/.local/share/virtualenvs/bb-server-cloud-migrate-h2IgRdlA/lib/python3.8/site-packages/atlassian/rest_client.py", line 236, in request
    response.raise_for_status()
  File "/home/mdavis/.local/share/virtualenvs/bb-server-cloud-migrate-h2IgRdlA/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitbucket.org/2.0/workspaces/a-workspace-name/projects
```

Getting a 400: Bad Request on a POST for an item that already exists totally makes sense. So how do I do this "create" in an idempotent way? I saw that there's also a "Project" method in `projects.py` (singular vs. the plural "Projects") which has an "update" method. The update method uses a PUT instead of a POST, so great, I thought! I just need to use that. But when I try to call that method like so...

```
bitbucket_cloud.workspaces.get(args.workspace)projects.update(
    key="ABC",
    name="ABC Project",
    description="A useful description",
    is_private=True
)
```

I get `AttributeError: 'Projects' object has no attribute 'update'`. Similarly, the lint/debugger in VSCode doesn't show the `update` method as an available method in "projects".

I'm new to Python, so odds are I'm missing something here about how to call this method...but if not, then this seems like a bug.

### PR DESCRIPTION
**Pull request by Spacetown**
Add function mentioned in #757. @rodalli Can you check this on your side?

Closes #757.

### CODE REVIEW

**Review by rodalli — COMMENTED** [review]
Nice, thanks for the commit! Suggestions are just fixes for trivial typos/spelling errors in comments.

I'll be able to test the actual code tomorrow morning and will provide more useful feedback then.

**Comment by Spacetown** [comment]
@rodalli Thanks for the fixes.

**Comment by rodalli** [comment]
@Spacetown Sorry for the delay in taking a look at this change. I've installed your updates from your fork via pip, but I'm not seeing the .exists method present in any of the expected classes based on your changes.

Maybe you can tell me if I'm doing something wrong, or if you're seeing different (could be that I didn't install your changes correctly, although I followed [the instructions here](https://github.com/atlassian-api/atlassian-python-api/blob/master/CONTRIBUTING.rst#using-your-changes-before-theyre-live)).

Just to make sure I had your changes:
```
pip3 uninstall atlassian-python-api
```

Then, after installing from your fork and using tab complete in REPL to explore the structure, I find that the exists method isn't available where expected:
```
mdavis@mdavis-stinkpad:~/code/github/atlassian-python-api$ python3 -m pip install git+https://github.com/Spacetown/atlassian-python-api.git
Collecting git+https://github.com/Spacetown/atlassian-python-api.git
  Cloning https://github.com/Spacetown/atlassian-python-api.git to /tmp/pip-req-build-1x6qv376
  Running command git clone -q https://github.com/Spacetown/atlassian-python-api.git /tmp/pip-req-build-1x6qv376
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from atlassian-python-api==2.6.0) (2.23.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from atlassian-python-api==2.6.0) (1.15.0)
Requirement already satisfied: oauthlib in /usr/lib/python3/dist-packages (from atlassian-python-api==2.6.0) (3.1.0)
Requirement already satisfied: requests-oauthlib in /home/mdavis/.local/lib/python3.8/site-packages (from atlassian-python-api==2.6.0) (1.3.0)
Requirement already satisfied: deprecated in /home/mdavis/.local/lib/python3.8/site-packages (from atlassian-python-api==2.6.0) (1.2.12)
Requirement already satisfied: wrapt<2,>=1.10 in /home/mdavis/.local/lib/python3.8/site-packages (from deprecated->atlassian-python-api==2.6.0) (1.12.1)
Building wheels for collected packages: atlassian-python-api
  Building wheel for atlassian-python-api (PEP 517) ... done
  Created wheel for atlassian-python-api: filename=atlassian_python_api-2.6.0-py3-none-any.whl size=124909 sha256=a679173782abf82fa8afd9c73a6c4d97553a18f95a92ead64adacc11ee3a2f15
  Stored in directory: /tmp/pip-ephem-wheel-cache-6c8_08jk/wheels/2a/a4/1f/fecca1c25ace99a70faec4e7a4579e2a929c448ad904a3fd81
Successfully built atlassian-python-api
Installing collected packages: atlassian-python-api
Successfully installed atlassian-python-api-2.6.0

mdavis@mdavis-stinkpad:~/code/github/atlassian-python-api$ python3
Python 3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import atlassian
>>> atlassian.bitbucket.cloud.Workspaces.
atlassian.bitbucket.cloud.Workspaces.CONF_TIMEFORMAT               atlassian.bitbucket.cloud.Workspaces.get_link(
atlassian.bitbucket.cloud.Workspaces.bulk_headers                  atlassian.bitbucket.cloud.Workspaces.get_time(
atlassian.bitbucket.cloud.Workspaces.close(                        atlassian.bitbucket.cloud.Workspaces.log_curl_debug(
atlassian.bitbucket.cloud.Workspaces.data                          atlassian.bitbucket.cloud.Workspaces.mro(
atlassian.bitbucket.cloud.Workspaces.default_headers               atlassian.bitbucket.cloud.Workspaces.no_check_headers
atlassian.bitbucket.cloud.Workspaces.delete(                       atlassian.bitbucket.cloud.Workspaces.post(
atlassian.bitbucket.cloud.Workspaces.each(                         atlassian.bitbucket.cloud.Workspaces.put(
atlassian.bitbucket.cloud.Workspaces.experimental_headers          atlassian.bitbucket.cloud.Workspaces.request(
atlassian.bitbucket.cloud.Workspaces.experimental_headers_general  atlassian.bitbucket.cloud.Workspaces.resource_url(
atlassian.bitbucket.cloud.Workspaces.form_token_headers            atlassian.bitbucket.cloud.Workspaces.response
atlassian.bitbucket.cloud.Workspaces.get(                          atlassian.bitbucket.cloud.Workspaces.safe_mode_headers
atlassian.bitbucket.cloud.Workspaces.get_data(                     atlassian.bitbucket.cloud.Workspaces.url_joiner(
>>> atlassian.bitbucket.cloud.Workspaces.exists
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Workspaces' has no attribute 'exists'
```

It's not present in Projects either:

```
>>> atlassian.bitbucket.cloud.workspaces.Projects.e
atlassian.bitbucket.cloud.workspaces.Projects.each(
atlassian.bitbucket.cloud.workspaces.Projects.experimental_headers
atlassian.bitbucket.cloud.workspaces.Projects.experimental_headers_general
```

**Comment by Spacetown** [comment]
@rodalli The change sin't on master you have to use `git+https://github.com/Spacetown/atlassian-python-api.git@bitbucket_cloud_proj_repo_exists`.

**Comment by rodalli** [comment]
Pfffft. I can't believe I missed that. Sorry @Spacetown ! Thanks for pointing out my error.

I've tested the functionality with projects and repositories and all is working as I'd expect!

```
>>> bitbucket_cloud.workspaces.get('pgi-tools-archive').repositories.exists('cd.desktop-aws')
True
>>> bitbucket_cloud.workspaces.get('pgi-tools-archive').repositories.exists('cd.desktop-awsq')
False
```

Nice job! 👍🏻

**Review by rodalli — APPROVED** [review]
I've tested the functionality with projects and repositories and all is working as I'd expect!

```
>>> bitbucket_cloud.workspaces.get('pgi-tools-archive').repositories.exists('cd.desktop-aws')
True
>>> bitbucket_cloud.workspaces.get('pgi-tools-archive').repositories.exists('cd.desktop-awsq')
False
```

Nice job! 👍🏻

**Pull request merged**
