### PR TITLE
[Jira]: Migrate get all projects methods to use paginated endpoint for Jira Cloud.

### PR DESCRIPTION
**Pull request by marinone94**
* Migrate "get all projects" methods to use paginated endpoint for Jira Cloud.
* Update docs.
* Use the correct method in the archive project method.

### CODE REVIEW

**Comment by gonchik** [comment]
Hi @marinone94 , 
for the first iteration it sounds good. 

Main idea, just make quite easy steps for understanding code by non-developers

**Comment by gonchik** [comment]
How about wrap other methods?

**Comment by marinone94** [comment]
What do you mean?

**Comment by gonchik** [comment]
@marinone94  i meant wrap other rest api requests

**Pull request merged**
