### PR TITLE
Prepare for Bitbucket API 2.0

### PR DESCRIPTION
**Pull request by tuxmaster5000**
My idea for https://github.com/atlassian-api/atlassian-python-api/issues/232
It will only contains the base part, so it will not break anything.  ( I hope)
The API 2.0 endpoints must be added, because I can't test it without an cloud account.

### CODE REVIEW

**Comment by gonchik** [comment]
Hi!
Thanks for your idea  and preparation. 
What do you think if we will use  a field cloud instead of  standalone in rest class?
Of course it's easy win :) to be compatible with cloud API. 

Also, what do you think reuse that lib as git submodule and small overwrap of auth. 
https://bitbucket.org/atlassian/python-bitbucket/src/master/pybitbucket/auth.py
?

or we can continue use the 2 versions of end-points

**Comment by tuxmaster5000** [comment]
I have take an look at:
https://bitbucket.org/atlassian/python-bitbucket/src/master/pybitbucket/auth.py
I think here using an wrapper will let us ran in trouble, because not all endpoints in the source starts with: rest/api/VERSION ... I have seen some calls that shows to rest/insights, rest/git-lfs/ and so on.

**Comment by mashayev** [comment]
Any plan to merge it soon?

**Comment by gonchik** [comment]
@tuxmaster5000  Thanks for the PR. 
I have a little bit inversed the field of rest client api as mostly lib works with standalone.

**Pull request merged**
