### PR TITLE
Fix bitbucket cloud commits #1071

### PR DESCRIPTION
**Pull request by sreway**
- Fix each commit obj
- Fix get commit message
- Fix get commit author

### CODE REVIEW

**Comment by gonchik** [comment]
#1071

**Comment by gonchik** [comment]
@sreway  thanks could you investigate more code please?

**Comment by sreway** [comment]
@gonchik ok)

**Comment by Spacetown** [comment]
@sreway If you link the issue you can get 20$: https://github.com/atlassian-api/atlassian-python-api/issues/1071#issuecomment-1304503682

**Pull request merged**
