### PR TITLE
[Bitbucket] Fix pagination for cloud requests

### PR DESCRIPTION
**Pull request by sergey-p3**
Exception raised when requesting pull requests which exceed single page: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitbucket.org/2.0/repositories/XXXX/pullrequests/?q=state+%3D+%22OPEN%22+OR+state+%3D+%22MERGED%22+or+state%3D%22DECLINED%22&page=2/&q=state+%3D+%22OPEN%22+OR+state+%3D+%22MERGED%22+or+state%3D%22DECLINED%22

Next argument returned by the response contains full url including original params and next page. The issue is that the params are passed as duplicates to the following request along with the trailing / after provided url.

### CODE REVIEW

**Comment by sti0** [comment]
Hi @spusnei-pbsc ,
this fixes the issue. Could you make the PR ready to merge?
Thanks

**Review by sti0 — APPROVED** [review]
Works. With this fix it is possible to receive the full list of PR.

**Comment by spusnei-pbsc** [comment]
@sti0 done

**Comment by sti0** [comment]
@gonchik what are your thoughts on this one? The PR pagination is broken atm.

Thank you.

**Comment by sti0** [comment]
@sergey-p3 could you make this work? There are some issues with flake8 and black. Otherwise I can do. Thanks

**Comment by Spacetown** [comment]
@gonchik This can be closed as duplicate of #841.

**Comment by gonchik** [comment]
Thanks!

**Pull request closed without merging**
