### PR TITLE
[Bitbucket] Add OO interface for projects and repositories in bitbucket server.

### PR DESCRIPTION
**Pull request by Spacetown**
Add first OO interfaces with a test response for each function.
Validate size of paged response.
Extend VSCode workspace with file association for the responses.

### CODE REVIEW

**Comment by gonchik** [comment]
Looks interesting

**Comment by Spacetown** [comment]
But interesting is not good enough.

**Comment by Spacetown** [comment]
Should I add more endpoints in this PR or do it in a separate one?

**Comment by gonchik** [comment]
Let's do in separate one.
I will play with changes soon

**Pull request merged**
