### PR TITLE
Bitbucket Cloud: Add PR diff/patch/diffstat

### PR DESCRIPTION
**Pull request by flichtenheld**
* Added object for DiffStat and moved to its own
  file since it can be generated at different places
  in the API.

Signed-off-by: Frank Lichtenheld <frank@lichtenheld.com>

### CODE REVIEW

**Comment by gonchik** [comment]
@flichtenheld Could you adjust code based on the advice from codacy please ?
https://app.codacy.com/gh/atlassian-api/atlassian-python-api/pullRequest?prid=8434769

**Comment by flichtenheld** [comment]
> @flichtenheld Could you adjust code based on the advice from codacy please ? https://app.codacy.com/gh/atlassian-api/atlassian-python-api/pullRequest?prid=8434769

Yeah, I tried. Just caused different issues. Pushed next attempt just now.

**Comment by flichtenheld** [comment]
> > @flichtenheld Could you adjust code based on the advice from codacy please ? https://app.codacy.com/gh/atlassian-api/atlassian-python-api/pullRequest?prid=8434769
> 
> Yeah, I tried. Just caused different issues. Pushed next attempt just now.

So now only one issue remains:

> 1 blank line required before class docstring (found 0) (D203)

Are you sure about that one? There is literally not a single class in your code that fullfills this. All the existing ones that actually have class comments have them directly after the class statement. Wouldn't it be better to disable D203 and use D211 ("No blank lines allowed before class docstring") instead?

**Comment by gonchik** [comment]
Let me found how to make an exclusion for codacity

**Pull request merged**
