### PR TITLE
Feature/api client post

### PR DESCRIPTION
**Pull request by satyamsoni2211**
- Enhanced APIClient to include JSON parameters in post request

### CODE REVIEW

**Comment by satyamsoni2211** [comment]
I have opened this pull request to directly post data as JSON instead of converting the data into JSON encoded string and passing in post API. I am using the same patch in my existing code in my organization at HSBC.

**Comment by gonchik** [comment]
Hi!
Unfortunately, to me is unclear the purpose of wrapping into json field for request method. 
As it's not cover for all other requests

**Comment by gonchik** [comment]
Do you have plan to provide a PR with all needful changes?

**Comment by satyamsoni2211** [comment]
The purpose of using JSON parameters is to pass dict of dict as **JSON** directly to request body for the creation of JSD ticket. I was facing issues with post requests for multiple hierarchies of dict for custom fields containing sub child fields and options. User would now be able to use data/JSON parameters, any of them as per there convenience.

**Comment by satyamsoni2211** [comment]
I have updated PR to be backward compatible, now user can either use JSON encoded values_dict or pass it as is, the argument will be chosen based on the type of payload.

**Comment by gonchik** [comment]
@satyamsoni2211  Thank you for your update. 
Actually,  my question was about the data transferring to python-requests method.
As you updated the parameters for request 
```
request(self, method='POST', path='/', data=None, flags=None, params=None, json=None, headers=None,
                files=None, trailing=None)
```
but here that json will not transfer.
```
response = self._session.request(
            method=method,
            url=url,
            headers=headers,
            data=data,
            timeout=self.timeout,
            verify=self.verify_ssl,
            files=files,
            proxies=self.proxies
        )

```

based on that, could you provide your main pain about setting the json? Maybe to make wrapper for all type of requets (GET, POST , PUT etc )

**Comment by satyamsoni2211** [comment]
I will check this out and make the required changes

**Comment by satyamsoni2211** [comment]
For future versions, I will make changes to all kinds of wrapper to accommodate the changes. Since I faced this issue with create request, I added this to the specific method, since now request method can accept JSON, I will test other methods out and can make the similar changes later on.

**Comment by gonchik** [comment]
thanks

**Pull request merged**
